apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver-httpd
spec:
  capacity:
    storage: 10Gi
  acessModes:
    - ReadWriteMany
  nfs:
    path: /<nfs filestore data share name in gcloud>
    server: <nfs filestore IP in gcloud>

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: fileserver-httpd
spec:
  acessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver-httpd
  resources: 
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: httpd
    template:
      metadata:
        labels:
          app: httpd
        spec:
          containers:
          - image: httpd:latest
            name: httpd
            ports: 
          - containerPort: 80
            name: httpd

          volumeMounts:
          - name: fileserver-httpd
            mountPath: /usr/local/apache2/htdocs/
          volumes:
          - name: fileserver-httpd
          persistentVolumeClaim:
            claimName: fileserver-httpd
            
 