apiVersion: v1
kind: Pod
metadata: 
  name: app-php
spec:
- name: app-php
  image: <user>/app-php:1.0
  ports:
  - containerPort: 80
----
apiVersion: v1
kind: Service
metadata:
  name: nodePort-php-service
spec:
  type: NodePort
  selector:
    app: app-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005