apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  acessModes:
    - ReadWriteOnce
  resources: 
    storage: 100Mi
 